# access
#
passwd:
  users:
    - name: core
      password_hash: "$6$SfuvSSLq$YJe.Qtnglb7Ct2oCSU1qlMWZOmWzGiN.Ue53gLe4rZ6meV9wv6rpt8LZEd4uGBsPqvR/I/UPNRunR4vjSw6jI1"
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDQRo/P7J0so62IWM9I2ZYc38lUTYZS3u0FH2D6FDrVZFoYk8jzb3zE3SYpCrE20vLekqtJi3Ljzu6OKMG/+2jyN9aAPbOssbQpUjfXya+yuWA6pkB13/usZv/NjXH1PODw2KE8+lei406hLHJvV7J74Y3RMUuKghSXc4POswHXh1hzG6LeuG4DRqDTEUrYb2RUm6VR/OrW9DVnmLmK7t7+aU7opMq0sxX36s8qqdtUqqSPjECtc17S/zrI2GPKovinzyXue0EPebOp4xBMIU24WG9rnQjXASxTW/SCZNg6QcjASCH36zmI7q0eaxsB3JXNmEt/hCbohcn0e0aLemHizPR/x81sYmSFzro1vY+lOBe60BaxF9lScioJ8cDJ/RR2CisLCQVVwUwJjeopENNU4nRauG27H3V92GMHyQQqcihqStFs3JPHyPrstwxOYWHDNNtOoHcuKo9mA3a8zh0t8y82GGbVyG+fTp2lLs/lI72ptY4XptOxSBiTcqw2GjsfmqMUybUOO6Oq4E4ifXBlnkBz55wmpMp5Kt16kKrs9ajSbDlxTiIE1LpGcxE1ZXPcy/7nyKvJyQ3DxLQsq3lmceDYizpcL7wL56em2jeDIJySGB79/QupmIyyMDqFwRP1dK92ZWEYGqxFMkQ0UuhVggGtJPBNUZjont8h3PllOw==

#    - name: czhujer
#      groups: [ sudo, docker ]

storage:
  files:
    - filesystem: "root"
      path:       "/etc/hostname"
      mode:       0644
      contents:
        inline: alg-core-s2

# etcd
#
etcd:
  # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
  # specify the initial size of your cluster with ?size=X
  discovery: https://discovery.etcd.io/c63219c0da13c7d1715718f0e6874834
  advertise_client_urls:       http://172.23.56.151:2379
  initial_advertise_peer_urls: http://192.168.221.11:2380
  #
  listen_client_urls:          http://0.0.0.0:2379
  listen_peer_urls:            http://192.168.221.11:2380

#
networkd:
  units:
    - name: 00-eth0.network
      contents: |
        [Match]
        Name=eth0

        [Network]
        DNS=172.23.56.145
        Address=172.23.56.151/28
        Gateway=172.23.56.145
    - name: 01-eth1.network
      contents: |
        [Match]
        Name=eth1

        [Network]
        #DNS=192.168.221.1
        Address=192.168.221.11/24
        #Gateway=10.0.0.1
